SHELL := /bin/bash

# Executables discovery (prefer .venv if present, fallback to PATH)
PYTHON ?= $(shell if [ -f .venv/bin/python ]; then echo .venv/bin/python; else command -v python3 || echo python3; fi)
RUFF ?= $(shell if [ -f .venv/bin/ruff ]; then echo .venv/bin/ruff; else command -v ruff || echo ruff; fi)
MYPY ?= $(shell if [ -f .venv/bin/mypy ]; then echo .venv/bin/mypy; else command -v mypy || echo mypy; fi)
LINT_IMPORTS ?= $(shell if [ -f .venv/bin/lint-imports ]; then echo .venv/bin/lint-imports; else command -v lint-imports || echo lint-imports; fi)
TWINE ?= $(shell if [ -f .venv/bin/twine ]; then echo .venv/bin/twine; else command -v twine || echo twine; fi)

# Coverage floor. Raise it when you add tests; never lower it to make a build
# pass. It is a ratchet, not a target.
COV_FAIL_UNDER ?= 98

# GPG key to use for signing release artifacts.
# Auto-detected from the first available secret key; override with:
#   make release GPG_KEY_ID=<fingerprint or email>
GPG_KEY_ID ?= $(shell gpg --list-secret-keys --keyid-format LONG 2>/dev/null | awk '/^sec/{print $$2}' | head -1 | cut -d'/' -f2)

.PHONY: setup test test-cov test-blind integration-test clean lint format verify release \
        publish-test publish help ci-local docs docs-build docs-sync build-web-docs docs-serve serve-docs

# ============================================================
# Documentation (MkDocs Material)
# ============================================================

## docs: Build the MkDocs web documentation
docs: docs-build

## docs-build: Build MkDocs HTML documentation site
docs-build: build-web-docs

## docs-sync: Mirror the root CHANGELOG into the documentation site
docs-sync:
	@echo "[NSE] Syncing CHANGELOG into docs/web/release-notes/…"
	@printf '<!-- Generated by `make docs-sync`. Edit CHANGELOG.md at the repository root. -->\n\n' > docs/web/release-notes/changelog.md
	@cat CHANGELOG.md >> docs/web/release-notes/changelog.md

## build-web-docs: Compile MkDocs Markdown & docstrings to HTML
build-web-docs: docs-sync
	@echo "[NSE] Building MkDocs web documentation…"
	$(PYTHON) -m mkdocs build

## docs-serve: Launch MkDocs live documentation preview server (http://127.0.0.1:8000)
docs-serve: serve-docs

## serve-docs: Start MkDocs dev server with hot-reload
serve-docs:
	@echo "[NSE] Starting MkDocs live documentation server (http://127.0.0.1:8000)…"
	$(PYTHON) -m mkdocs serve

# ============================================================
# Setup
# ============================================================

## setup: Bootstrap the development environment (venv + dependencies)
setup:
	@bash scripts/dev-setup.sh

# ============================================================
# Tests
# ============================================================

## test: Run the unit test suite (no root required)
test:
	@echo "[NSE] Running unit tests…"
	$(PYTHON) -m pytest tests/ -v

## test-cov: Run the unit tests with coverage, enforcing the ratchet
test-cov:
	@echo "[NSE] Running unit tests with coverage (floor: $(COV_FAIL_UNDER)%)…"
	$(PYTHON) -m pytest tests/ --cov=nse --cov-report=term-missing \
		--cov-report=xml --cov-fail-under=$(COV_FAIL_UNDER)

## integration-test: Run the privileged oracle tests and the YAML suite as root
integration-test:
	@echo "[NSE] Running integration tests (requires sudo)…"
	sudo -E $(PYTHON) -m pytest tests/ -v -m "integration"
	sudo -E $(PYTHON) -m nse.cli.runner --file tests/test_suite.yaml

## test-blind: Prove a blind parser FAILS the suite instead of passing it
##             This is the meta-test for the oracle. Expect a non-zero exit
##             from the runner; the target succeeds when that happens.
test-blind:
	@echo "[NSE] Blindness meta-test: the runner must FAIL when the parser sees nothing…"
	@if sudo -E NSE_FORCE_BLIND=1 $(PYTHON) -m nse.cli.runner --file tests/test_suite.yaml; then \
		echo "!!! FAIL: a blind oracle reported success. The runner is not trustworthy."; \
		exit 1; \
	else \
		echo "==> OK: a blind oracle correctly failed the suite."; \
	fi

# ============================================================
# Code Quality & Verification
# ============================================================

## lint: Check styling (ruff), type hints (mypy), and import boundaries (import-linter)
lint:
	@echo "[NSE] Running static analysis checks (ruff)…"
	$(RUFF) check nse/ tests/
	$(RUFF) format --check nse/ tests/
	@echo "[NSE] Running static type checks (mypy)…"
	$(MYPY) nse/
	@echo "[NSE] Checking import boundaries (import-linter)…"
	$(LINT_IMPORTS)

## format: Automatically format the Python codebase
format:
	@echo "[NSE] Auto-formatting python codebase (ruff)…"
	$(RUFF) check --fix nse/ tests/
	$(RUFF) format nse/ tests/

## verify: Run static analysis and the unit tests with the coverage ratchet
verify: lint test-cov

## ci-local: Execute the full local CI pipeline
ci-local: verify docs-build
	@echo "[NSE] Running PyPI smoke test…"
	@python3 -m venv .smoke_test_venv && \
		.smoke_test_venv/bin/pip install -e ".[cli]" >/dev/null && \
		.smoke_test_venv/bin/python -c "import nse; from nse.core.pipeline import run_test_pipeline; print('Smoke PyPI OK')" && \
		rm -rf .smoke_test_venv
	@$(MAKE) integration-test
	@$(MAKE) test-blind
	@echo "========================================================================"
	@echo "[NSE] Local CI pipeline PASSED."
	@echo "========================================================================"

# ============================================================
# Build & release
# ============================================================

## release: Build the headless nse/ Python package into release/
release: clean verify
	@echo "[NSE] Preparing release artifacts…"
	mkdir -p release/
	$(PYTHON) -m pip install --upgrade build twine
	$(PYTHON) -m build --outdir release/
	cp Dockerfile release/
	cd release && sha256sum * > SHA256SUMS
	@echo "[NSE] Signing SHA256SUMS with GPG… (key: $(GPG_KEY_ID))"
	gpg --clearsign $(if $(GPG_KEY_ID),--local-user $(GPG_KEY_ID),) --output release/SHA256SUMS.asc release/SHA256SUMS
	@echo "========================================================================"
	@echo "Release preparation complete. Artifacts in release/:"
	@ls -la release/
	@echo "Tag the commit BEFORE publishing: what is on PyPI must map to a git ref."
	@echo "========================================================================"

## publish-test: Upload the built python packages to TestPyPI
publish-test:
	@echo "[NSE] Uploading package to TestPyPI…"
	$(TWINE) upload --repository testpypi release/network_sandbox_engine-*.tar.gz release/network_sandbox_engine-*-py3-none-any.whl

## publish: Upload the built python packages to PyPI
publish:
	@echo "[NSE] Uploading package to PyPI…"
	$(TWINE) upload release/network_sandbox_engine-*.tar.gz release/network_sandbox_engine-*-py3-none-any.whl

# ============================================================
# Housekeeping
# ============================================================

## clean: Remove build artifacts, caches, and temp files
clean:
	rm -rf release/ dist/ build/ network_sandbox_engine.egg-info/ htmlcov/ coverage.xml .coverage
	find nse tests -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find nse tests -name "*.pyc" -delete 2>/dev/null || true

## help: Show this help message
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/## /  /'
